[build]
  command = "vita build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-formspree"

[[plugins]]
  package = "netlify-plugin-cloudinary"
